package com.example.rhservice.domain.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Inheritance;
import jakarta.persistence.InheritanceType;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@Table(name = "app_users")
@Inheritance(strategy = InheritanceType.JOINED)
/**
 * Abstract base entity representing a generic application user.
 *
 * <p>Design notes:
 * - Uses JPA {@code JOINED} inheritance so concrete subclasses map to their own tables.
 * - Marked {@code abstract} because only concrete subclasses (e.g. {@link Employee}, {@link Admin}) should be persisted directly.
 * - Lombok generates getters/setters and other boilerplate to keep the class focused on state (Single Responsibility).
 *
 * Fields are documented so IDEs and generated Javadoc show intent for each property and for generated accessors.
 */
public abstract class User {

    /** Primary key generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Full name for the user. Generated accessor: {@code getName()}/{@code setName(String)}. */
    private String name;

    /** Contact telephone number. */
    private String telephone;

    /** Postal or street address. */
    private String address;

    /** Bank account identifier for payments. */
    private String bankAccount;
}